Change CI shell

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -8,7 +8,9 @@ jobs:
     env:
       MAINVER: "5.2.4"
       ALTVER: "5.1.5"
-
+    defaults:
+      run:
+        shell: bash --login -eo pipefail {0}
     steps:
     - name: Checkout
       uses: actions/checkout@v2
@@ -42,7 +44,7 @@ jobs:
         source /etc/environment && source /opt/swiftbox/env.sh && source $HOME/.swiftbox/env.sh
         if [ `which swift` != "$HOME/.swiftbox/toolchain/swift-$MAINVER/usr/bin/swift" ]
         then
-          echo "::error::Swift $ALTVER is not removed correctly."
+          echo "::error::Swift $MAINVER is not installed correctly."
           exit 2
         fi
         swiftc -v
@@ -52,8 +54,8 @@ jobs:
         swiftbox list
         sudo swiftbox list
         swiftbox use $ALTVER
-        swiftbox list
         source /etc/environment && source /opt/swiftbox/env.sh && source $HOME/.swiftbox/env.sh
+        swiftbox list
         if [ `which swift` != "$HOME/.swiftbox/toolchain/swift-$ALTVER/usr/bin/swift" ]
         then
           echo "::error::Swift $ALTVER is not selected correctly."
@@ -74,7 +76,6 @@ jobs:
 
     - name: Test Swift status
       run: |
-        source /etc/environment && source /opt/swiftbox/env.sh && source $HOME/.swiftbox/env.sh
         echo "\$PATH=$PATH"
         if [ `which swift` != "$HOME/.swiftbox/toolchain/swift-$MAINVER/usr/bin/swift" ]
         then
@@ -85,7 +86,6 @@ jobs:
 
     - name: Test Swift compiler
       run: |
-        source /etc/environment && source /opt/swiftbox/env.sh && source $HOME/.swiftbox/env.sh
         swift test.swift
         swiftc test.swift -o test && ./test
 
@@ -94,7 +94,6 @@ jobs:
 
     - name: Test Swift disabled
       run: |
-        source /etc/environment && source /opt/swiftbox/env.sh && source $HOME/.swiftbox/env.sh
         if [ `which swift` != /usr/* ]
         then
           echo "::error::swiftbox is not closed correctly."
@@ -105,6 +104,9 @@ jobs:
     container:
       image: ubuntu:20.04
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash --login -eo pipefail {0}
     steps:
     - name: Checkout
       uses: actions/checkout@v2
@@ -124,20 +126,14 @@ jobs:
       run: ./swiftbox.sh get nightly
 
     - name: Test Swift status
-      shell: bash
       run: |
-        source /etc/environment
-        source /opt/swiftbox/env.sh
         echo "\$PATH=$PATH"
         ./swiftbox.sh list
         which swift
         swiftc -v
 
     - name: Test Swift compiler
-      shell: bash
       run: |
-        source /etc/environment
-        source /opt/swiftbox/env.sh
         swift test.swift
         swiftc test.swift -o test && ./test
 
@@ -145,6 +141,9 @@ jobs:
     container:
       image: centos:8
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash --login -eo pipefail {0}
     steps:
     - name: Checkout
       uses: actions/checkout@v2
@@ -164,20 +163,14 @@ jobs:
       run: yum install which -y
 
     - name: Test Swift status
-      shell: bash
       run: |
-        source /etc/environment
-        source /opt/swiftbox/env.sh
         echo "\$PATH=$PATH"
         ./swiftbox.sh list
         which swift
         swiftc -v
 
     - name: Test Swift compiler
-      shell: bash
       run: |
-        source /etc/environment
-        source /opt/swiftbox/env.sh
         swift test.swift
         swiftc test.swift -o test && ./test
 
@@ -185,6 +178,9 @@ jobs:
     container:
       image: amazonlinux:2
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash --login -eo pipefail {0}
     steps:
     - name: Install tar and gzip
       run: yum install tar gzip -y
@@ -207,17 +203,13 @@ jobs:
       run: yum install which -y
 
     - name: Test Swift status
-      shell: bash
       run: |
-        source /etc/environment
-        source /opt/swiftbox/env.sh
         echo "\$PATH=$PATH"
         ./swiftbox.sh list
         which swift
         swiftc -v
 
     - name: Test Swift compiler
-      shell: bash
       run: |
         source /etc/environment
         source /opt/swiftbox/env.sh
