Add path test

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -25,12 +25,27 @@ jobs:
       run: swiftbox lookup $MAINVER
 
     - name: Test swiftbox get with sudo
-      run: sudo swiftbox get $MAINVER
+      run: |
+        sudo swiftbox get $MAINVER
+        source /etc/environment && source /opt/swiftbox/env.sh
+        if [ `which swift` != "/opt/swiftbox/toolchain/swift-$MAINVER/usr/bin/swift" ]
+        then
+          echo "::error::Swift $MAINVER is not installed correctly."
+          exit 2
+        fi
+        swiftc -v
 
     - name: Test swiftbox get
       run: |
         swiftbox get $MAINVER
         swiftbox get $ALTVER
+        source /etc/environment && source /opt/swiftbox/env.sh && source $HOME/.swiftbox/env.sh
+        if [ `which swift` != "$HOME/.swiftbox/toolchain/swift-$MAINVER/usr/bin/swift" ]
+        then
+          echo "::error::Swift $ALTVER is not removed correctly."
+          exit 2
+        fi
+        swiftc -v
 
     - name: Test swiftbox list and use
       run: |
@@ -39,6 +54,11 @@ jobs:
         swiftbox use $ALTVER
         swiftbox list
         source /etc/environment && source /opt/swiftbox/env.sh && source $HOME/.swiftbox/env.sh
+        if [ `which swift` != "$HOME/.swiftbox/toolchain/swift-$ALTVER/usr/bin/swift" ]
+        then
+          echo "::error::Swift $ALTVER is not selected correctly."
+          exit 2
+        fi
         swiftc -v
 
     - name: Test swiftbox clean
